---
galaxy_info:
  author: "Your Name"
  description: Role to create files using custom module
  license: GPL-3.0-or-later
  min_ansible_version: "2.9"
  galaxy_tags:
    - file
    - custom
    - module
dependencies: []
